-- BajriX marketplace schema.
-- Key modelling decision: PRODUCT (catalogue entry, one row per real-world item) is separate
-- from SELLER_LISTING (one seller's offer for that product: price, stock, MOQ).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE sellers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(150) NOT NULL,
    city       varchar(100) NOT NULL,
    status     varchar(20)  NOT NULL CHECK (status IN ('APPROVED', 'PENDING', 'REJECTED')),
    created_at timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         varchar(64)  NOT NULL UNIQUE,
    category_id bigint       NOT NULL REFERENCES categories (id),
    name        varchar(200) NOT NULL,
    brand       varchar(100) NOT NULL,
    unit        varchar(30)  NOT NULL,
    description text,

    -- Denormalised read model for browsing/sorting. It describes only what a BUYER can see:
    -- ACTIVE listings of APPROVED sellers. Maintained transactionally by ProductSummaryRepository
    -- whenever a listing or a seller's status changes. Lets the catalogue query avoid
    -- aggregating over 10M listings on every request.
    offer_count           integer       NOT NULL DEFAULT 0,  -- visible offers (incl. out of stock)
    available_offer_count integer       NOT NULL DEFAULT 0,  -- offers that can actually be ordered
    min_price             numeric(12,2),                     -- best price among available offers
    max_price             numeric(12,2),

    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE seller_listings (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    bigint        NOT NULL REFERENCES products (id),
    seller_id     bigint        NOT NULL REFERENCES sellers (id),
    price         numeric(12,2) NOT NULL CHECK (price > 0),
    stock         integer       NOT NULL CHECK (stock >= 0),
    min_order_qty integer       NOT NULL CHECK (min_order_qty >= 1),
    status        varchar(20)   NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    version       bigint        NOT NULL DEFAULT 0,   -- optimistic locking
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now(),
    -- A seller can have at most one listing per product (stopping = INACTIVE, not delete).
    CONSTRAINT uq_listing_product_seller UNIQUE (product_id, seller_id)
);

-- Indexes -------------------------------------------------------------------------------
-- Seller's "my listings" screen (filter by status, newest first).
CREATE INDEX idx_listings_seller ON seller_listings (seller_id, status, updated_at DESC);
-- (product_id, seller_id) unique index above also serves "all offers for a product".

-- Substring search on name/brand (ILIKE '%term%') stays index-assisted at 1M products.
CREATE INDEX idx_products_name_trgm  ON products USING gin (name gin_trgm_ops);
CREATE INDEX idx_products_brand_trgm ON products USING gin (brand gin_trgm_ops);

-- Default browse order and price sorting, restricted to products buyers can actually see.
CREATE INDEX idx_products_visible_rank  ON products (available_offer_count DESC, name, id) WHERE offer_count > 0;
CREATE INDEX idx_products_visible_price ON products (min_price, id) WHERE offer_count > 0;
CREATE INDEX idx_products_category      ON products (category_id, name) WHERE offer_count > 0;
